### ISSUE TITLE
Customize onError behavior

### ISSUE THREAD

**Issue by petrbela** [vercel-labs/react-tweet#25]
Right now, `notFoundOnError` either throws an error or displays the predefined "Not Found" text. It might be more flexible to provide an onError callback to render a custom message or hide it completely. Or is the intention to wrap the error in an ErrorBoundary?

**Comment by lfades** [comment]
An `onError` callback might not do it because it involves client-side logic and the tweet can be used in the server (RSC). A custom Error component can do that, however I still need to research what's the right way to do it.
