### ISSUE TITLE
'no-store' fetch in `getTweet()` breaks static rendering

### ISSUE THREAD

**Issue by imtsuki** [vercel-labs/react-tweet#66]
https://github.com/vercel-labs/react-tweet/blob/f621e96f470b386dba7240e55be1258400facb13/packages/react-tweet/src/api/get-tweet.ts#L54

In app dir with `export const dynamicParams = false`, it throws

```
DynamicServerError: Dynamic server usage: no-store fetch
...
digest: 'DYNAMIC_SERVER_USAGE'
```

**Comment by lfades** [comment]
I remember adding this because Next.js cache was not being helpfup during my testing of multiple states. I'll take a look!
