### ISSUE TITLE
[Bug] Custom component - MediaImg is not working

### ISSUE THREAD

**Issue by nekochan0122** [vercel-labs/react-tweet#70]
![image](https://user-images.githubusercontent.com/47508893/228379869-d12d4a26-a2ea-458b-9093-efc9a711eb1e.png)

the `draggable` should be `false`.

https://neko-nextjs-blog.vercel.app/posts/hello-world#twitter

**Comment by nekochan0122** [comment]
And the image optimization seems doesn't work either.

**Comment by lfades** [comment]
Please provide more details about what's not working and how should it work.

**Comment by nekochan0122** [comment]
> Please provide more details about what's not working and how should it work.

what's not working: `MediaImg` Custom Component.

how should work: I use Next/Image to replace `AvatarImg` and `MediaImg`, but only `AvatarImg` is working, `MediaImg` should work too.
![Untitled](https://user-images.githubusercontent.com/47508893/229041190-169f97b7-07ce-4904-8349-3b9b52d2e131.png)

> not only image optimization, the props also not working. ( the `draggable` should be `false`. )

**Comment by tywayne** [comment]
What version of `react-tweet` do you have installed? A bugfix was provided for the `MediaImg` in `v2.0.1` that may resolve at least part of your issue.

The other piece (the `draggable` prop) is most likely because the props sent through by the internal media component sets `draggable="true"`, so you have to override it. 

```tsx
/*
your code, since you spread props after setting draggable, `{...props}` will 
override your draggable prop back to the internal value, which is `true`
*/
MediaImg: (props) => <Image quality={100} draggable={false} {...props} />

// you could either swap positions so your overrides come last like this
MediaImg: (props) => <Image {...props} quality={100} draggable={false} />

// or be sure to merge them before applying to your <Image /> component like this
MediaImg: (props) => {
  const customProps = {
    ...props,
    draggable: true,
    quality: 100
  }
  return <Image {...customProps} />
}
```

**Comment by nekochan0122** [comment]
Thank you for your explain @tywayne, I'm using `v2.0.0` and I can't update it:

```
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for react-tweet@2.0.1

This error happened while installing a direct dependency of 

The latest release of react-tweet is "2.0.0".

Other releases are:
  * beta: 1.6.0
```

**Comment by tywayne** [comment]
Ahh, interesting. Yeah, looks like that release happened here on the repo but was never published to npm.

**Comment by nekochan0122** [comment]
It's still `2.0.0` here:

![image](https://user-images.githubusercontent.com/47508893/229923825-ea3f412a-df67-41a6-a3a3-dba5d3b3fb1e.png)

**Comment by tywayne** [comment]
> It's up now.
> 
> I forgot to publish, I'm sorry!

@lfades Hey, @nekochan0122 and I are both still not seeing this published to NPM. Showing `v2.0.0` as latest - https://www.npmjs.com/package/react-tweet
