### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by GuruPrakashDavala** [vercel-labs/react-tweet#73]
I am using Next js version 13.

The `EmbeddedTweet` component from this package throws `CSS Imported by a Dependency` issue.
[https://nextjs.org/docs/messages/css-npm](https://nextjs.org/docs/messages/css-npm)

I am fetching the tweet data from own API and passing it to the EmbeddedTweet component.

Attached are screenshots for your reference. Any suggestions will be greatly appreciated.

Package.json file:

![Package json snapshot](https://user-images.githubusercontent.com/17375695/230714992-7c8a5b90-e587-4fe3-9da3-ea188fe58af0.png)

Component file (short example):

![React tweet component snapshot](https://user-images.githubusercontent.com/17375695/230715901-dcf4c00c-a3af-4b6f-9309-52c320b32b43.png)

**Comment by tywayne** [comment]
This comment on a previous issue reporting a similar error might be of assistance.

https://github.com/vercel-labs/react-tweet/issues/39#issuecomment-1472555146

**Comment by GuruPrakashDavala** [comment]
Thank you @tywayne 

`transpilePackages: ['react-tweet']` resolved the issue.
