### ISSUE TITLE
Tweet component returns Tweet Not Found

### ISSUE THREAD

**Issue by JoshuaRotimi** [vercel-labs/react-tweet#94]
Tweet makes a request to this endpoint (https://react-tweet.vercel.app/api/tweet/1672473372305899520) and returns a 404 error.

<img width="577" alt="Screenshot 2023-07-05 at 10 52 48" src="https://github.com/vercel-labs/react-tweet/assets/62189959/e05aea13-6920-4177-9ef6-173270d3c806">

**Comment by lfades** [comment]
This was fixed in https://github.com/vercel-labs/react-tweet/pull/95.
